#!/bin/bash

mkdir rover_mission
cd rover_mission

touch log1.txt log2.txt log3.txt

mv log1.txt mission_log.txt

echo "Files with .log extension:"
find . -name "*.log"

echo "Contents of mission_log.txt:"
cat mission_log.txt

echo "Lines containing 'ERROR':"
grep "ERROR" mission_log.txt

echo "Number of lines in mission_log.txt:"
wc -l mission_log.txt

echo "Current date and time:"
date

echo "CPU usage snapshot:"
top -b -n 1 | head -n 10

echo "Shutdown scheduled in 10 minutes (this line is commented out for safety)"
# sudo shutdown +10
